### ISSUE TITLE
Ошибка =(

### ISSUE THREAD

**Issue by DeliWyleS** [By1337/BAirDrop#10]
[00:27:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEnvironment()" because "this.world" is null
[00:27:42 WARN]:        at BAirDrop-1.0.9.jar//org.by1337.bairdrop.locationGenerator.CGenerator.getLocation(CGenerator.java:66)
[00:27:42 WARN]:        at BAirDrop-1.0.9.jar//org.by1337.bairdrop.CAirDrop$3.run(CAirDrop.java:692)
[00:27:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:27:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:27:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:27:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:27:42 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:27:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by By1337** [comment]
Похоже на эту проблему https://github.com/By1337/BAirDrop/issues/2
