### ISSUE TITLE
Не работает после перезагрузки

### ISSUE THREAD

**Issue by Medved0546** [By1337/BAirDrop#2]
ядро - paper 1.16.5
плагины - ACubelets, AdvancedEnchantments, ajLeaderboards, AntiRelog, AtributeHeadsPlace*, BAirDrop, BankPlus, BattlePass, BKCommonLib, BottledExp, BountyHunters, BungeeGuard, ChatEx, ChatItem, Chunky, Citizens, CleanroomGenerator, ClearLag, CMI, CMIEInjector*, CMILib, CommandTimer, ConditionalEvents, CraftEnhance, DecentHolograms, DeluxeMenus, EasyPayments, FastAsyncWorldEdit (WorldEdit), FunUtillity, GooDTimEMessages, HexAirDrop, HolographicDisplays, HolyBoers, HyperReseller, HyperSpeedTasks, IllegalStack, IRandomTeleport*, ItemEdit, ItemJoin, ItemsAdder, JShader, LagAssist, LibsDisguises, LightAPI, LightCheck, LoneLibs, LPX, LuckPerms, MagicCosmetics, Matrix, MineResetLite, MiningBlock, ModelEngine, MoneyFromMobs, MultiEconomy*, Multiverse-Core, MyCommand, MythicMobs, MythicMobsGUI, NBTAPI, ODailyQuests, PhysicsControl, PlaceholderAPI, PlayerPoints, PrimeAlchemist, ProtectionStones, ProtocolLib, PSAddon, PSUApi*, RE4TNT, RocketPlaceholders, SCore, ShopGUIPlus, SKLibrary, spark, TAB, UltimateAutoRestart, UltimateClans, Vault, ViaVersion, WorldGuard, zAuctionHouseV3, zKoth

BAirDrop protocollib dh последней версии

я создаю аирдроп устанавливаю статическую локацию через гуи и всё работает но после перезагрузки
[07:42:11 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:12 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:13 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:14 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:15 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:16 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:17 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:18 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:19 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:20 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:21 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:22 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:23 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:24 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:25 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:26 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:27 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:28 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!
[07:42:29 ERROR]: [BAirDrop] use-only-static-loc = true, но статическая локация равна null!

и координаты в гуи аридропа пропадают
причём после /bair reload продолжает работать нормально

так же при включении в логах есть какая-то шелуха
[07:41:49] [Server thread/INFO]: [BAirDrop] Enabling BAirDrop v1.0.9.1
[07:41:49] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
	at org.bukkit.Location.deserialize(Location.java:1137) ~[patched_1.16.5.jar:git-Paper-794]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-794]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.16.5.jar:git-Paper-794]
	at org.by1337.bairdrop.configManager.CConfig.loadConfiguration(CConfig.java:130) ~[?:?]
	at org.by1337.bairdrop.BAirDrop.onEnable(BAirDrop.java:88) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[07:41:49] [Server thread/WARN]: java.lang.ClassNotFoundException: com.monfection.monfection.a
[07:41:49] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
[07:41:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[07:41:49] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[07:41:49] [Server thread/WARN]: 	at org.by1337.bairdrop.util.Metrics.<init>(Metrics.java:86)
[07:41:49] [Server thread/WARN]: 	at org.by1337.bairdrop.BAirDrop.onEnable(BAirDrop.java:90)
[07:41:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[07:41:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:41:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[07:41:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[07:41:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[07:41:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599)
[07:41:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298)
[07:41:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[07:41:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[07:41:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:41:49] [Server thread/ERROR]: [BAirDrop] Ошибка мира в аирдропе new1 статическая локация не загружена!
[07:41:49] [Server thread/INFO]: Аирдроп new1 загружен!
[07:41:49] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: BAirDrop [1.0.9.1]
[07:41:49] [Server thread/INFO]: Плагин успешно включён за 48ms

**Comment by By1337** [comment]
В ошибке пишет "unknown world" при десериализации локации, попробуй удалить locations.yml. и заново сгенерировать локации.
Также один из аирдропов выкинул ошибку " [BAirDrop] Ошибка мира в аирдропе new1 статическая локация не загружена!"
Скорей всего имя мира было указано не правильно или мир был удалён.
Также хочу заменить что последняя версия плагина 1.0.9, а не 1.0.9.1. На spigotmc.org плагин выкладывал не я и я не могу знать какие там были внесены изменения.

**Comment by Medved0546** [comment]
я установил ваш плагин можете пж подсказать что я не так делаю - https://youtu.be/0H1EBctA-DE

**Comment by By1337** [comment]
Открой плагин с помощью winrar найди в нём plugin.yml и измени softdepend на 
```yaml
softdepend:
  - DecentHolograms
  - ProtocolLib
  - PlaceholderAPI
  - Multiverse-Core
```

**Comment by Medved0546** [comment]
спс все ошибки с консоли пропали и корды терь устанавливаются без bair reload
а в чём проблема была то?
я слышал что Multiverse-Core ужасный плагин на миры но он мне нужен чтоб пустые миры генерировать

**Comment by By1337** [comment]
Плагин включался до загрузки мира и не мог его найти
